WebApplication1/WebApplication1/Models/Customer.cs
namespace WebApplication1.Models
{
    public class Customer
    {
        public int ID { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }
        public string ApplicationUserId { get; set; }
        public bool? IsDeleted { get; set; }
        public virtual List<Order> Orders { get; set; }
        public virtual List<CustomerSelected_SupplierProduct> SelectedItems { get; set; }

        public int TotalPoint { get; set; }

        public virtual List<Review> Reviews { get; set;}

    }
}

WebApplication1/WebApplication1/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.ViewModel;
using WebApplication1.Models;
using WebApplication1.repo;
using System.Security.Claims;
using WebApplication1.Helper;

namespace WebApplication1.Controllers
{
    public class CustomerController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        Ireposatory<Customer> repo;
        Ireposatory<Product> productRepo;
        Ireposatory<Supplier_Product> supProductRepo;
        Ireposatory<CustomerSelected_SupplierProduct> selectedItemsRepo;
        Ireposatory<Supplier_Product_Order> Supplier_Product_OrderRepo;
        Ireposatory<Order> ordersRepo;
        public CustomerController(Ireposatory<Order> _ordersRepo,Ireposatory<CustomerSelected_SupplierProduct> _selectedItemsRepo, Ireposatory<Supplier_Product> _supProductRepo,Ireposatory<Product> _productRepo,Ireposatory<Customer> _repo,UserManager<ApplicationUser> _userManager, Ireposatory<Supplier_Product_Order> Supplier_Product_OrderRepo) {
            repo = _repo;
            userManager = _userManager;
            productRepo = _productRepo;
            supProductRepo = _supProductRepo;
            selectedItemsRepo = _selectedItemsRepo;
            ordersRepo = _ordersRepo;
            this.Supplier_Product_OrderRepo = Supplier_Product_OrderRepo;
            //context = _context;
        }

        public async Task<IActionResult> index()
        {
            Claim idClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            string userid = idClaim.Value;
            Claim nameClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Name);
            string username = nameClaim.Value;
            Customer customer = repo.getall().FirstOrDefault(c => c.ApplicationUserId == userid);
            CustomerProfileVM c = new CustomerProfileVM();
            c.CustomId = customer.ID;
            c.userName = username;
            ViewData["id"] = c.CustomId;
            ViewData["Username"] = c.userName;
            List<Supplier_Product> products = supProductRepo.getall("Product");
            //ViewData["ProductName"] = ;
           // int Id;
            //foreach (Supplier_Product s in products)
            //{
            //    Id = s.ProductID;
            //    Product p = productRepo.getbyid(Id);
            //    //ViewData["ProductName"] = p.Name;
            //    //ViewData["ProductImage"] = p.ImageName;
            //    //ViewData["SupplierId"] = s.ID;
             
            //}
            return View(products);
        }
        public async Task< IActionResult> CustomerProfile()
        {
            Claim idClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            string userid = idClaim.Value;
            //Customer c=repo.getbyidCustom(c=>c.ID==id && c.ApplicationUserId==c.ApplicationUser.Id);
           // Customer customer=repo.getbyid(id);
            Customer customer = repo.getall().FirstOrDefault(c => c.ApplicationUserId == userid);
            ApplicationUser user = await userManager.FindByIdAsync(customer.ApplicationUserId);
            CustomerProfileVM c=new CustomerProfileVM();
            c.CustomId = customer.ID;
            //ViewData["id"] = c.CustomId;
            c.userName = user.UserName;
            c.Address=user.Address;
            c.Phone = user.PhoneNumber;
            c.Email = user.Email;
            c.Image = user.ImageName;

            return View(c);
        }
        [HttpPost]
        public async Task< IActionResult> CustomerProfile(CustomerProfileVM customer)
        {
           Customer customer1 = repo.getbyid(customer.CustomId);
            ApplicationUser user = await userManager.FindByIdAsync(customer1.ApplicationUserId);
            if (customer != null)
            {
               //Customer oldEmp = new Customer();
                customer1.ApplicationUser.Address=customer.Address;
                customer1.ApplicationUser.PhoneNumber = customer.Phone;
                customer1.ApplicationUser.Email = customer.Email;
                customer1.ApplicationUser.UserName = customer.userName;
                customer1.ApplicationUser.ImageName = ImagesHelper.UploadImg(customer.ImageFile, "ProfileIMG");
                repo.update(customer1);
                return RedirectToAction("CustomerProfile", new {id=customer.CustomId});
            }
            return View(customer);
            
        }
        public IActionResult ShowCart()
        {
            Claim idClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            string userid = idClaim.Value;
            List<Customer> customers = repo.getall();
            Customer customer = customers.FirstOrDefault(c => c.ApplicationUserId == userid);
            List<CustomerSelected_SupplierProduct> selectedItems = selectedItemsRepo.getall().Where(s => s.CustomerID == customer.ID).ToList(); ;
            List<SelectedItemsInCartVM> selectedItemsInCarts = new List<SelectedItemsInCartVM>();

            double totalprice = 0;

            foreach (CustomerSelected_SupplierProduct item in selectedItems)
            {
                Supplier_Product s1 = supProductRepo.getbyid(item.Supplier_ProductID);
                Product p = productRepo.getbyid(s1.ProductID);
                SelectedItemsInCartVM selectedItems1=new SelectedItemsInCartVM()
                {
                    Price = s1.Price,
                    CustomId=customer.ID,
                    Description=p.Description,
                    Image=p.ImageName,
                    productName=p.Name,
                    Quantity= item.Quantity,
                    selectedItemId =item.ID,
                    totalPrice= item.TotalPrice,
                };
                totalprice += selectedItems1.totalPrice;
                selectedItemsInCarts.Add(selectedItems1);
            }
            ViewData["totalprice"] = totalprice;
            return View("Cart",selectedItemsInCarts);
            //return View(selectedItemsInCarts);
        }
       
        
        
        
        //public void AddToCart(int productId)//SelectedItemsInCartVM selectedItems)
        //{
        //   Claim idClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
        //    string userid = idClaim.Value;
        //    List<Customer> customers =repo.getall();
        //    Customer customer = customers.FirstOrDefault(c=>c.ApplicationUserId==userid);
        //    Supplier_Product s = supProductRepo.getbyid(productId);
        //    Product p = productRepo.getbyid(s.ProductID);
        //   CustomerSelected_SupplierProduct selected_SupplierProduct = new CustomerSelected_SupplierProduct();
        //    selected_SupplierProduct.CustomerID = customer.ID;
        //    selected_SupplierProduct.Quantity = s.Quantity;
        //    selected_SupplierProduct.TotalPrice = s.Price;
        //    selected_SupplierProduct.Supplier_ProductID = productId;
        //    selectedItemsRepo.create(selected_SupplierProduct);
            
        //}
      
        
        
        public IActionResult Delete(int selectId)
        {
            //List<CustomerSelected_SupplierProduct> s1 = selectedItemsRepo.getall();
            
              CustomerSelected_SupplierProduct s = selectedItemsRepo.getbyid(selectId);
              selectedItemsRepo.delete(s);
              return Json(new { totalprice = selectedItemsRepo.getall().Sum(s => s.TotalPrice), totalquantity = selectedItemsRepo.getall().Sum(s => s.Quantity) });

            //List <CustomerSelected_SupplierProduct> s1 = selectedItemsRepo.getall();
            //return RedirectToAction("ShowCart");
        }
        public IActionResult Increase(int selectId, int quantity, int price)
        {
            Claim idClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            string userid = idClaim.Value;
            List<Customer> customers = repo.getall();
            Customer customer = customers.FirstOrDefault(c => c.ApplicationUserId == userid);

            CustomerSelected_SupplierProduct s = selectedItemsRepo.getbyid(selectId);
            Supplier_Product supplier_Product = supProductRepo.getbyid(s.Supplier_ProductID);
            s.TotalPrice = quantity * price;
            s.Quantity = quantity;
            supplier_Product.Quantity = quantity;
            selectedItemsRepo.update(s);
            return Json(new { producttotalprice = s.TotalPrice, totalprice = selectedItemsRepo.getall().Sum(s => s.TotalPrice), totalquantity = selectedItemsRepo.getall().Where(s => s.CustomerID == customer.ID).Sum(s => s.Quantity) });
        }


        public void Order(int customId)
        {
            List<CustomerSelected_SupplierProduct> selectedItems = selectedItemsRepo.getall().Where(s => s.CustomerID == customId).ToList();

           // Customer customer = repo.getbyid(customId);
            Order order1 = new Order()
            {
                CrediteNumber = "123",
                CustomerID = customId,
                Date = DateTime.Now,
                OrderState = "doesn't token",
                TotalPrice = selectedItems.Sum(t => t.TotalPrice),
                PaidMethod = "Cash",
                //DelivaryID=1
            };
            ordersRepo.create(order1);
            Supplier_Product_Order Supplier_Product_Order;
            foreach (CustomerSelected_SupplierProduct item in selectedItems)
            {
                Supplier_Product_Order = new Supplier_Product_Order();

                Supplier_Product_Order.OrderID = order1.ID;
                Supplier_Product_Order.TotalPrice = item.TotalPrice;
                Supplier_Product_Order.Supplier_ProductID = item.Supplier_ProductID;
                Supplier_Product_Order.Quntity = item.Quantity;

                selectedItemsRepo.delete(item);

WebApplication1/WebApplication1/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow;
using NuGet.Protocol.Core.Types;
using System.Security.Claims;
using System.Security.Policy;
using WebApplication1.Models;
using WebApplication1.repo;

namespace WebApplication1.Controllers
{
    public class ProductsController : Controller
    {
        UserManager<ApplicationUser> userManager;
        Ireposatory<Customer> CustomerRepo;
        Ireposatory< Supplier_Product> Supplierreproduct;
        Ireposatory<Category> CategoryRepositry;
        Ireposatory<Product> ProductRepositry;
        Ireposatory<Review> ReviewRepositry;
        Ireposatory<Supplier_Product> supProductRepo;
        Ireposatory<CustomerSelected_SupplierProduct> selectedItemsRepo;

        public ProductsController
            (UserManager<ApplicationUser> userManager,Ireposatory<Supplier_Product> Supplierreproduct, Ireposatory<Category> CategoryRepositry, Ireposatory<Product> ProductRepositry, Ireposatory<Customer> CustomerRepo
           ,Ireposatory<Review> ReviewRepositry, Ireposatory<Supplier_Product> supProductRepo, Ireposatory<CustomerSelected_SupplierProduct> selectedItemsRepo)
        {
            this.userManager=userManager;
            this.Supplierreproduct = Supplierreproduct;
            this.ProductRepositry = ProductRepositry;
            this.CategoryRepositry = CategoryRepositry;
            this.CustomerRepo = CustomerRepo;
            this.supProductRepo= supProductRepo;
            this.selectedItemsRepo = selectedItemsRepo;
            this.ReviewRepositry = ReviewRepositry;
        }


        public IActionResult Index()
        {
            ViewData["category"] = CategoryRepositry.getall() ;
            List<Supplier_Product> ProductModel = Supplierreproduct.getall("Product","Supplier").Where(sp=>sp.Supplier.IsDeleted==false).ToList();
            return View("Index", ProductModel);
        }
         

        public async Task<IActionResult> Deatils(int id)
        {
            Supplier_Product ProductModel = Supplierreproduct.getall("Product", "Reviews").FirstOrDefault(s=>s.ID==id);
            ProductModel.Product = ProductRepositry.getall("Brand").FirstOrDefault(p=>p.ID==ProductModel.ProductID);
           
            
            ProductModel.Reviews = ReviewRepositry.getall("Customer").Where(r=>r.Supplier_ProductID==id).ToList();  
            foreach(Review item in ProductModel.Reviews)
            {
                item.Customer = CustomerRepo.getall("ApplicationUser").FirstOrDefault(c=>c.ID==item.CustomerId);
            }

            if (ProductModel.Quantity>0)
            {
                ViewData["Availability"] = "In Stock";
                ViewData["Style"] = "text-success";
            }
            else
            {
                ViewData["Availability"] = "Un Available";
                ViewData["Style"] = "text-danger";
            }
            Claim idClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            string userid = idClaim.Value;
            ApplicationUser applicationUser = await userManager.FindByIdAsync(userid);
            ViewData["imagename"] = applicationUser.ImageName;
            ViewData["relatedProducts"] = Supplierreproduct.getall("Product").Where(sp=>sp.Product.BrandID== ProductModel.Product.BrandID) ; 
            return View("Deatils", ProductModel);
        }
       
        public IActionResult productbycategory(int categoryID)
        {
            if(categoryID==0)
            {
                List<Supplier_Product> AllProducts = Supplierreproduct.getall("Product", "Supplier").Where(sp => sp.Supplier.IsDeleted == false).ToList();
                return Json(AllProducts);//new { name = AllProducts }//new { name = "" }, new { name = "" }
            }
            
            List<Supplier_Product> CategoryProduct = Supplierreproduct.getall("Product", "Supplier").Where(sp => sp.Supplier.IsDeleted == false && sp.Product.CategoryID == categoryID).ToList();
            return Json(CategoryProduct);//new { name=CategoryProduct }// name= new { age=50} },new { name=""

        }

        public void AddToCart(int supplierproductID, int quantity)//SelectedItemsInCartVM selectedItems)
        {
            Claim idClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            string userid = idClaim.Value;
            List<Customer> customers = CustomerRepo.getall();
            Customer customer = customers.FirstOrDefault(c => c.ApplicationUserId == userid);
            Supplier_Product s = supProductRepo.getbyid(supplierproductID);
            Product p = ProductRepositry.getbyid(s.ProductID);
            CustomerSelected_SupplierProduct selected_Item = selectedItemsRepo.getall().Where(s => s.CustomerID == customer.ID).FirstOrDefault(item => item.Supplier_ProductID == supplierproductID);

            if (selected_Item == null)
            {
                CustomerSelected_SupplierProduct selected_SupplierProduct = new CustomerSelected_SupplierProduct();
                selected_SupplierProduct.CustomerID = customer.ID;
                selected_SupplierProduct.Supplier_ProductID = supplierproductID;
                selected_SupplierProduct.Quantity = quantity;
                selected_SupplierProduct.TotalPrice = s.Price * quantity;
                selectedItemsRepo.create(selected_SupplierProduct);
            }
            else
            {
                selected_Item.Quantity += quantity;
                selected_Item.TotalPrice = s.Price* selected_Item.Quantity;
                selectedItemsRepo.update(selected_Item);
            }
            
        }


        public async Task<IActionResult> GetTotalQuantity(string name)
        {
            ApplicationUser applicationUser = await userManager.FindByNameAsync(name);
            Customer customer = CustomerRepo.getall().FirstOrDefault(c=>c.ApplicationUserId==applicationUser.Id);
            return Json(selectedItemsRepo.getall().Where(s=>s.CustomerID== customer.ID).Sum(s=>s.Quantity));
        }


        public IActionResult review(int supplierproductid, string comment)
        {
            Claim idClaim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            string userid = idClaim.Value;
            Customer customer = CustomerRepo.getall().FirstOrDefault(c => c.ApplicationUserId == userid);
            DateTime dateTime = DateTime.Now;
            Review review = new Review();
            review.Supplier_ProductID = supplierproductid;
            review.ReviewText = comment;
            review.Date = dateTime;
            review.CustomerId = customer.ID;
            ReviewRepositry.create(review);
            return Json(review);
        }


    }
}

WebApplication1/WebApplication1/Views/Customer/Cart.cshtml
@using WebApplication1.ViewModel
@model List<SelectedItemsInCartVM>

@{
    ViewData["Title"] = "Cart";

    Layout = "_productLayout";
}

<div class="site__body pt-3">
    <div class="cart block m-5">
        <div class="container">
            <table class="cart__table cart-table">
                <thead class="cart-table__head">
                    <tr class="cart-table__row">
                        <th class="cart-table__column cart-table__column--image">Image</th>
                        <th class="cart-table__column cart-table__column--product">Product</th>
                        <th class="cart-table__column cart-table__column--price">Price</th>
                        <th class="cart-table__column cart-table__column--quantity">Quantity</th>
                        <th class="cart-table__column cart-table__column--total">Total</th>
                        <th class="cart-table__column cart-table__column--remove"></th>
                    </tr>
                </thead>
                <tbody class="cart-table__body" id="tbody">



                    @foreach (var item in Model)
                    {
                       
                        

                        <tr class="cart-table__row" id="TR_@item.selectedItemId">
                            <td class="cart-table__column cart-table__column--image">
                                <a href="#">
                                    <img src="@item.Image" alt="">
                                </a>
                            </td>
                            <td class="cart-table__column cart-table__column--product">
                                <a href="#"
                               class="cart-table__product-name">@item.productName</a>
                                <ul class="cart-table__options">
                                    <li>Color: Yellow</li>
                                    <li>Material: Aluminium</li>
                                </ul>
                            </td>
                            <td class="cart-table__column cart-table__column--price" data-title="Price">@item.Price</td>
                            <td class="cart-table__column cart-table__column--quantity" data-title="Quantity">
                                <div class="input-number">
                                    <input class="form-control input-number__input" 
                                       id="quantity_@item.selectedItemId"
                                       onchange="IncreasePrice(@item.selectedItemId,@item.Price)" type="number" min="1" value="@item.Quantity">
                                    <div class="input-number__add"></div>
                                    <div class="input-number__sub"></div>
                                </div>
                            </td>
                            <td id="totalprice_@item.selectedItemId" class="cart-table__column cart-table__column--total" data-title="Total">
                                @item.totalPrice
                            </td>
                            <td class="cart-table__column cart-table__column--remove">
                                <button type="button"
                                    onclick="Delete(@item.selectedItemId)"
                                    class="btn btn-light btn-sm btn-svg-icon">
                                    <svg width="12px" height="12px">
                                        <use xlink:href="/images/sprite.svg#cross-12"></use>
                                    </svg>
                                </button>
                            </td>
                        </tr>
                    
                   }


                </tbody>
            </table>
            <div class="cart__actions row justify-content-end" style="padding-right:12px">
                <div class="cart__buttons">
                    <a class="btn btn-primary" asp-action="Index" asp-controller="Products">Continue Shopping</a>
                    @*<a class="btn btn-primary cart__update-button">Update Cart</a>*@
                </div>
            </div>

            <div class="row justify-content-end pt-5">
                <div class="col-12 col-md-7 col-lg-6 col-xl-5">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-title">Cart Totals</h3>
                            <table class="cart__totals">
                                <thead class="cart__totals-header">
                                    <tr>
                                        <th>Subtotal</th>
                                        <td id="Subtotal">$@ViewBag.totalprice</td>
                                    </tr>
                                </thead>
                                <tbody class="cart__totals-body">
                                    <tr>
                                        <th>Shipping</th>
                                        <td>
                                            $25.00<div class="cart__calc-shipping">
                                                <a href="#">
                                                    Calculate
                                                    Shipping
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Tax</th>
                                        <td>$0.00</td>
                                    </tr>
                                </tbody>
                                <tfoot class="cart__totals-footer">
                                    <tr>
                                        <th>Total</th>
                                        <td id="Total">$@(ViewBag.totalprice+25)</td>
                                    </tr>
                                </tfoot>
                            </table>
                            <a class="btn btn-primary btn-xl btn-block cart__checkout-button"
                               @{
                                    int CustomerId;
                               if(Model.FirstOrDefault()==null)
                                   {
                                       CustomerId=0;
                                   
                                   }
                                
                                    else 
                                    {
                               CustomerId=Model.FirstOrDefault().CustomId;
                                    }
                               }
                               onclick="Check(@CustomerId)">Proceed to checkout
                           </a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>







@section Scripts{
       <script>
            
           $("#CartIcon").html(@Model.Sum(s=>s.Quantity));

        function IncreasePrice(id, p) {
                $.ajax({
                    type: 'get',
                    url: "/Customer/Increase",
                    data: { "selectId": id, "quantity": $(`#quantity_${id}`).val(), "price": p },
                    success: function (result) {
                    $(`#totalprice_${id}`).html(result.producttotalprice);
                    $("#Subtotal").html("$" + result.totalprice);
                    $("#Total").html("$" + (result.totalprice + 25));
                    $("#CartIcon").html(result.totalquantity);
                    }
                })
            }


            function Delete(id) {

                $.ajax({
                    type: 'POST',
                    url: "/Customer/Delete",
                    data: { "selectId": id },
                    success: function (result) {
                    $(`#TR_${id}`).remove();
                    $("#Subtotal").html("$"+result)
                    if (result == 0) {
                        $("#Total").html("$" + result)
                    }
                    else 
                    {
                        $("#Total").html("$" + (result + 25))
                    }
                    $("#CartIcon").html(result.totalquantity);

                    }
                })
            }


            function Check(id) {
                $.ajax({
                    type:'post',
                    url: "/customer/order",
                    data: { "customid":id },
                    success: function (result) {
                    $("#tbody").remove();
                    $("#CartIcon").html(0);
                    }
                })
            }


        
       </script>


}

WebApplication1/WebApplication1/Views/Customer/index.cshtml
@using WebApplication1.Models;
@model List<Supplier_Product>

@{
    ViewData["Title"] = "index";
}

<h1>index</h1>
<p>
    <a asp-action="CustomerProfile">@User.Identity.Name</a>
</p>
<p>
    <a asp-action="Create">Create New</a>
</p>
<p>
    <a asp-action="ShowCart">Cart</a>
</p>
@foreach (Supplier_Product item in Model)
        {

    <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title" id="hfive">@item.Product.Name</h5>
            <p class="card-text" id="parag1">@item.Product.ImageName</p>
            <p class="card-text" id="parag2">@item.Product.Description</p>
            <p class="card-text" id="parag3">@item.ID</p>
            <p class="card-text" id="parag4">@item.Quantity</p>
            <p class="card-text" id="parag5">@item.Price</p>
            <button onclick="GetCart(@item.ID)" >Add To Cart</button>
            @*<input asp-for="@item.ID" type="text" id="parag3">*@
        </div>
    </div>

        }

@*@section Scripts{
    <script src="/lib/jquery/dist/jquery.min.js"></script>
 <script>
        //var name = $("#parag3").text();
        function GetCart(name) {
            
            var img = $("#parag1").text();
            $.ajax({
                type: 'POST',
                url: "/Customer/AddToCart",
                data: {"productId": name },
                success: function (result) {
                    console.log("Success");
                }
            });
        };
 </script>
}
*@